name: Generate snake game from github contribution grid
on:
  schedule:
    - cron: '0 9 12 * *' # Runs at 9 AM every 12th day of the month
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#00BC91&color_dots=#d1fff0,#a3fce1,#77f7d1,#4af2c1,#00BC91
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#00BC91&color_dots=#d1fff0,#a3fce1,#77f7d1,#4af2c1,#00BC91
            dist/github-snake-theme.svg?palette=github-light&color_snake=#00BC91&color_dots=#ffffff,#c3fcf0,#91f7e1,#61f2d1,#00BC91
            dist/ocean.gif?color_snake=#00BC91&color_dots=#d1fff0,#a3fce1,#77f7d1,#4af2c1,#00BC91
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push github-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
